### ISSUE TITLE
DLC - Frog Species

### ISSUE THREAD

**Issue by brunosfreitas** [FrankRuis/ats_cheatsheet#1]
First of all, congrats!! Your tool is amazing, it has a great usability and it's easy and fast to use.

With the new DLC a new Frog Species was added and with it some new needs and old species were adjusted. 

I tried to update your source code but the goods.json file was too clutered to add new needs. IE: "Paste" food and "Boots" clothing.

Could you please add the Frog race and its updates to your selector?

Thanks

**Comment by FrankRuis** [comment]
Thanks! I have just updated the cheat sheet with the latest data from the wiki, it should also be reflected in the live github pages page after a `ctrl + F5` refresh. I have not played the DLC yet, so you might need to double check if the current setup is correct. :)

The goods.json is indeed not meant to be human-readable, I use the python scripts in the `src` folder to generate it from the data files I found on the wiki (with some hacky hardcoded cleaning of the source data). The needs and species are hardcoded in the `index.html` file since that was quicker than parsing the data files haha
